### ISSUE TITLE
QSimSimulator.run should only simulate once when there are no intermediate measurements

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/qsim#191]
Instead, it prints out
```
Provided circuit has no intermediate measurements. It may be faster to sample from the final state vector. Continuing with one-by-one sampling.
```
Is there a reason this simple optimization was not implemented?

**Comment by 95-martin-orion** [comment]
This is meant to direct users to `QSimSimulator.simulate()`. That method simulates once and returns the full state vector, allowing the user to sample as needed.

The goal of this was to force users to be intentional about which execution method they want to use, but if there's no purpose for one-by-one sampling when all measurements are terminal, we could redirect that path to a simulate-and-sample method. What do you think?

**Comment by kevinsung** [comment]
I think we should perform the optimization automatically. In practice, without the optimization, the `run` method is essentially useless.

**Comment by 95-martin-orion** [comment]
The redirect should now work at HEAD - I'll cut a fresh qsimcirq release shortly.
