### ISSUE TITLE
Make C++ to Python state vector copying cheaper

### ISSUE THREAD

**Issue by 95-martin-orion** [quantumlib/qsim#237]
Users have noted that calling `qsim_simulator.simulate()` from Cirq takes considerably longer than the qsim simulation itself. This is likely due to the added cost of copying results from C++ to Python, which in theory can be avoided.

To resolve this issue, the pybind layer should ensure that results from Python are captured in C++ objects without copying.

**Comment by sergeisakov** [comment]
Calling `results = qsim_simulator.simulate()` from Cirq takes about the same time as the qsim simulation itself. The results are not copied from C++ to Python. Calling `results.state_vector()` from Cirq may take considerable time for large circuits. The problem is in Cirq not in qsimcirq, see line 215 in https://github.com/quantumlib/Cirq/blob/master/cirq/sim/state_vector_simulator.py.

**Comment by 95-martin-orion** [comment]
Aha! That means this is a victim of [Cirq PR 3115](https://github.com/quantumlib/Cirq/pull/3115), which is meant to prevent mutation of the state vector in other simulators. I'll redirect this issue to Cirq.
