### ISSUE TITLE
Nonexistent psim_test.py file mentioned in documentation

### ISSUE THREAD

**Issue by gecrooks** [quantumlib/qsim#55]
The docs refer to a file called `qsim_test.py`, which does not appear to exist. The link goes nowhere. 

https://github.com/quantumlib/qsim/blob/master/docs/cirq_interface.md#use-qsim-from-python-without-cirq

**Comment by 95-martin-orion** [comment]
That's an artifact of a discarded change from pre-release times...let me send out a patch.

Just for reference, this is meant to point to [qsimcirq_tests/qsim_test.py](https://github.com/quantumlib/qsim/blob/master/qsimcirq_tests/qsim_test.py). Because of how Python searches for modules, I'd recommend running it with `make run-py-tests` instead of the instructions in the doc, though.
