### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by viathor** [quantumlib/qsim#83]
Many links on the [qsimcirq pypi page](https://pypi.org/project/qsimcirq/) are broken. See for example the link to docs about input format.

We may also want to link to the [quantum supremacy dataset](https://datadryad.org/stash/dataset/doi:10.5061/dryad.k6t1rj8), especially if the files there are compatible with qsimcirq (fileformats used there are described in the enclosed README file).

(Not sure this is the right place to file.)

**Comment by 95-martin-orion** [comment]
This looks like a side-effect of (1) using the README as the long description for PyPI, and (2) using short links in the README, which break when ported to PyPI.

The fix is fairly simple (switch to full URL for links in the README) but I don't think it would appear on PyPI until a new qsim release went out. @iamvamsikrishnad, could you look into this? I'll auto-approve a release as long as the usual checks pass.
